services:
  # =======================
  # BookCatalog Service
  # =======================
  bookcatalog-api:
    image: vattamrajesh/bookcatalogservice:latest
    ports:
      - "8086:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: ${BOOKCATALOG_DB_CONNECTION}
    depends_on:
      - bookcatalog-db
    networks:
      - library-network

  bookcatalog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${BOOKCATALOG_DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - bookcatalog_db_data:/var/opt/mssql
    networks:
      - library-network

  # =======================
  # Hostel Management Service
  # =======================
  hostel-api:
    image: vattamrajesh/hostelmanagement:latest
    ports:
      - "8087:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: ${HOSTEL_DB_CONNECTION}
    depends_on:
      - hostel-db-library
    networks:
      - library-network

  hostel-db-library:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${HOSTEL_DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1440:1433"
    volumes:
      - hostel_db_data_library:/var/opt/mssql
    networks:
      - library-network

# =======================
# Networks
# =======================
networks:
  library-network:

# =======================
# Volumes
# =======================
volumes:
  hostel_db_data_library:
  bookcatalog_db_data:
